base_url = "https://unixis.fun"
title = "mrtnvgr::home"
description = "Egor`s personal website"
default_language = "en"
output_dir = "public"
compile_sass = true
minify_html = true
build_search_index = false

generate_feed = true
feed_filename = "feed.xml"

[markdown]
highlight_code = false
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
anchors = "on"

#=========================================================================================

[extra]

name = "Egor Martynov"
id = "mrtnvgr"
avatar = "img/avatar.svg"
links = [
  { name = "GitHub", icon = "github", url = "https://github.com/mrtnvgr" },
  { name = "Telegram", icon = "telegram", url = "https://t.me/mrtnvgr" },
  { name = "Email", icon = "email", url = "mailto:root@unixis.fun" },
]

sections = [
  { name = "blog", path = "/blog" },
]

default_theme = "rose-pine"

nav_separator = "::"
date_format = "%e %B %Y"

not_found_title = "404 | Not Found"
not_found_error_text = "Not Found"
not_found_recover_text = "« back to home »"
